default:
  image: $CI_REGISTRY/android/shared/docker-android:v1.0.0

before_script:
  - mkdir app/src/uiTest/assets
  - mkdir keystore
  - base64 -d - < "$TEST_USERS_CREDENTIALS_FILE" > app/src/uiTest/assets/users.json
  - base64 -d - < "$INTERNAL_API_FILE" > app/src/uiTest/assets/internal_api.json
  - base64 -d - < "$PRIVATE_PROPERTIES_FILE" > private.properties
  - export JAVA_TOOL_OPTIONS="-Dhttp.proxyHost=$( echo ${http_proxy##http://} | cut -d':' -f1 ) -Dhttp.proxyPort=$( echo ${http_proxy##http://} | cut -d':' -f2 ) -Dhttps.proxyHost=$( echo ${https_proxy##http://} | cut -d':' -f1 ) -Dhttps.proxyPort=$( echo ${https_proxy##http://} | cut -d':' -f2 ) -Dhttp.nonProxyHosts=\"$( echo $no_proxy | tr ',' '|' )\""
  - bundle install
  - !reference [.checkout-core-submodule, before_script] # included from checkout-core.gitlab-ci.yml
variables:
  ORG_GRADLE_PROJECT_useCoreGitSubmodule: "true" # see included checkout-core.gitlab-ci.yml for usage context

cache:
  - key: $CI_COMMIT_REF_SLUG
    policy: pull
    paths:
      - .gradle

stages:
  - analyse
  - localise
  - build
  - test
  - report
  - deploy

# See included checkout-core.gitlab-ci.yml for usage context
.checkout_core_job:
  variables:
    CHECKOUT_CORE_SUBMODULE: "true"

.build_job:
  stage: build
  extends: .checkout_core_job
  tags:
    - xlarge-k8s
  artifacts:
    paths:
      - app/build/outputs

.firebase_test_job:
  stage: test
  dependencies:
    - build_debug
  tags:
    - small
  before_script:
    - bundle install
    - ./buildSrc/setup_firebase_gcloud.sh

analyse:
  stage: analyse
  extends: .checkout_core_job
  cache:
    - key: $CI_COMMIT_REF_SLUG
      policy: pull-push
      paths:
        - .gradle
  tags:
    - medium
  script:
    - bundle exec fastlane analyse
  artifacts:
    expire_in: 1 month
    reports:
      codequality: config/detekt/reports/mergedReport.json


localise-sync-crowdin:
  stage: localise
  variables:
    I18N_SYNC_CROWDIN_PROJECT: 'android-mail-new'
  extends: .i18n-sync-crowdin-shared
  only:
    - master

localise-commit-locales:
  stage: localise
  variables:
    I18N_COMMIT_CROWDIN_PROJECT: 'android-mail-new'
  extends: .i18n-commit-locales-shared


build_debug:
  extends: .build_job
  script:
    - echo PROXY_TOKEN="$(curl -o - https://proxy.proton.black/token/get)" >> private.properties
    - bundle exec fastlane assembleDebug
    - bundle exec fastlane assembleTest


build_release:
  extends: .build_job
  only:
    - master
  script:
    - base64 -d - < "$PROTON_RELEASE_KEYSTORE_BASE64" > keystore/ProtonMail.keystore
    - bundle exec fastlane assembleRelease


run_unit_test:
  stage: test
  extends: .checkout_core_job
  tags:
    - xlarge-k8s
  dependencies:
    - build_debug
  script:
    - bundle exec fastlane unitTest

run_firebase_instrumentation_tests:
  extends: .firebase_test_job
  stage: test
  script:
    - bundle exec fastlane instrumentedTest

run_firebase_ui_tests:
  extends: .firebase_test_job
  script:
    - bundle exec fastlane uiTest


coverage report:
  stage: report
  extends: .checkout_core_job
  tags:
    - xlarge-k8s
  script:
    - bundle exec fastlane coverageReport
  artifacts:
    expire_in: 1 week
    paths:
      - app/build/reports
    reports:
      cobertura: app/build/reports/cobertura-coverage.xml


deploy_to_firebase:
  stage: deploy
  only:
    - master
  dependencies:
    - build_release
  tags:
    - small
  script:
    - echo $SERVICE_ACCOUNT_MAIL > /tmp/service-account.json
    - bundle exec fastlane deployToFirebase


include:
  - project: 'translations/generator'
    ref: master
    file: '/jobs/sync-crowdin.gitlab-ci.yml'

  - project: 'translations/generator'
    ref: master
    file: '/jobs/commit-locales.gitlab-ci.yml'

  - project: 'proton/mobile/android/proton-libs'
    ref: main
    file: '/ci/templates/checkout-core.gitlab-ci.yml'
