default:
  image: ${CI_REGISTRY}/android/shared/docker-android/oci:v2.0.1
  interruptible: true
  tags:
    - shared-small

before_script:
  - if [[ -f /load-env.sh ]]; then source /load-env.sh; fi
  - bundle config set path ${BUNDLE_GEM_PATH}
  - bundle config set without 'production'
  - bundle install

variables:
  # Use fastzip to improve cache times
  FF_USE_FASTZIP: "true"
  # Output upload and download progress every 5 seconds
  TRANSFER_METER_FREQUENCY: "5s"
  # Use no compression for artifacts
  ARTIFACT_COMPRESSION_LEVEL: "fastest"
  # Use low compression for caches
  CACHE_COMPRESSION_LEVEL: "fast"
  # Gem path
  BUNDLE_GEM_PATH: 'vendor/ruby'

# Makes sure we do not create separate merge request and branch pipelines.
# See https://docs.gitlab.com/ee/ci/yaml/workflow.html#switch-between-branch-pipelines-and-merge-request-pipelines
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

stages:
  - analyse
  - danger-review
  - localise
  - build
  - startReview
  - test
  - tag
  - deploy
  - stopReview

analyse:
  stage: analyse
  extends: .base_job
  tags:
    - shared-medium
  script:
    - bundle exec fastlane analyse
  artifacts:
    expire_in: 1 month
    reports:
      codequality: config/detekt/reports/mergedReport.json

danger-review:
  stage: danger-review
  tags:
    - shared-small
  when: always
  script:
    - bundle exec danger --fail-on-errors=false
  allow_failure: true
  variables:
    DANGER_GITLAB_API_TOKEN: $DANGER_GITLAB_API_TOKEN
  interruptible: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

i18n-send-crowdin:
  stage: localise
  extends: .i18n-sync-crowdin-shared
  tags:
    - shared-small
  variables:
    I18N_FILTER_OUT_ITEMS: 'proton-libs'
    I18N_SYNC_CROWDIN_PROJECT: 'android-mail-new'
    I18N_SYNC_BRANCH: 'master'
  only:
    - master

i18n-commit-locales:
  stage: localise
  extends: .i18n-commit-locales-shared
  tags:
    - shared-small
  variables:
    I18N_COMMIT_CROWDIN_PROJECT: 'android-mail-new'
    I18N_COMMIT_BRANCH_PUSH: 'master'
    I18N_COMMIT_BRANCH_ALLOWED: 'master'

build_dev_debug:
  extends: .build_job
  script:
    - base64 -d - < "$GOOGLE_SERVICES_JSON_FILE" > app/google-services.json
    - bundle exec fastlane setupUiTestsAssets
    - bundle exec fastlane assembleDevDebug
    - bundle exec fastlane assembleDevDebugAndroidTest

build_alpha_release:
  extends: .build_job
  script:
    - base64 -d - < "$PRIVATE_PROPERTIES_FILE" > private.properties
    - base64 -d - < "$SENTRY_PROPERTIES_FILE" > sentry.properties
    - base64 -d - < "$PROTON_RELEASE_KEYSTORE_BASE64" > keystore/ProtonMail.keystore
    - base64 -d - < "$GOOGLE_SERVICES_JSON_FILE" > app/google-services.json
    - bundle exec fastlane assembleAlphaRelease
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      # Always build on merge requests
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
      when: never

build_prod_release:
  extends: .build_job
  script:
    - base64 -d - < "$PRIVATE_PROPERTIES_FILE" > private.properties
    - base64 -d - < "$SENTRY_PROPERTIES_FILE" > sentry.properties
    - base64 -d - < "$PROTON_RELEASE_KEYSTORE_BASE64" > keystore/ProtonMail.keystore
    - base64 -d - < "$GOOGLE_SERVICES_JSON_FILE" > app/google-services.json
    - bundle exec fastlane assembleProdRelease
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      # Always build on merge requests
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
      when: never

startReview:
  stage: startReview
  tags:
    - shared-small
  before_script:
    - export REVIEW_APP_ARTIFACT_PATH="app/build/outputs/apk/alpha/release/app-alpha-release.apk"
    - echo ${REVIEW_APP_ARTIFACT_PATH}
  extends: .startReview
  dependencies:
    - build_alpha_release
  only:
    - merge_requests

stopReview:
  stage: stopReview
  extends: .stopReview
  tags:
    - shared-small
  rules:
    # The cleanup is always manual on a Merge Request
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
      allow_failure: true
    # But it's not needed when not on a Merge Request
    - when: never

run_unit_test:
  stage: test
  extends: .base_job
  tags:
    - xlarge-k8s
  dependencies:
    - build_dev_debug
  script:
    - base64 -d - < "$GOOGLE_SERVICES_JSON_FILE" > app/google-services.json
    - bundle exec fastlane unitTest
    - bundle exec fastlane coverageReport
  coverage: /Total.*?(\d{1,3}\.\d{0,2})%/
  artifacts:
    expire_in: 1 week
    paths:
      - build/reports
    reports:
      junit: ./**/build/test-results/test*/TEST-*.xml
      coverage_report:
        coverage_format: cobertura
        path: build/reports/cobertura-coverage.xml

run_firebase_proton_core_libs_tests:
  extends: .firebase_test_job
  allow_failure: true # Temporary, as long as we don't have a more specific test environment.
  script:
    - bundle exec fastlane coreLibsTest
  rules:
    - if: ('$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH') && ($NIGHTLY_ALPHA_BUILD == "true" || $INTERNAL_ALPHA_RELEASE == "true")

run_firebase_smoke_tests:
  extends: .firebase_test_job
  script:
    - bundle exec fastlane smokeTest
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: ('$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH') || $NIGHTLY_ALPHA_BUILD == "true"
      when: never
    - when: on_success

run_firebase_full_regression_tests:
  extends: .firebase_test_job
  script:
    - bundle exec fastlane fullRegressionTest
  rules:
    - if: ('$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH') && ($NIGHTLY_ALPHA_BUILD == "true" || $INTERNAL_ALPHA_RELEASE == "true")
    # Allow manual regression test runs on MRs if needed.
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
      allow_failure: true

tag_release:
  stage: tag
  extends: .base_job
  tags:
    - shared-small
  script:
    - bundle exec fastlane tagRelease
  rules:
    - if: ('$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH') && ($INTERNAL_ALPHA_RELEASE == "true")

deploy_to_firebase_dev:
  extends: .firebase_deploy_job
  script:
    - bundle exec fastlane deployToFirebaseDevGroup
  rules:
    - !reference [ .firebase_deploy_job, rules ]
    - if: $NIGHTLY_ALPHA_BUILD == "true"
      when: never
    - if: $INTERNAL_ALPHA_RELEASE == "true"
      when: never
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
      allow_failure: true

deploy_to_firebase_nightly:
  extends: .firebase_deploy_job
  script:
    - bundle exec fastlane deployToFirebaseNightlyGroup
  rules:
    - !reference [ .firebase_deploy_job, rules ]
    - if: $NIGHTLY_ALPHA_BUILD == "true"

deploy_to_firebase_alpha:
  extends: .firebase_deploy_job
  script:
    - bundle exec fastlane deployToFirebaseInternalAlphaGroup
  rules:
    - !reference [ .firebase_deploy_job, rules ]
    - if: $INTERNAL_ALPHA_RELEASE == "true"

distribute:debug:
  stage: deploy
  image: $CI_REGISTRY/tpe/test-scripts
  dependencies:
    - build_dev_debug
  rules:
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
      allow_failure: true
  script:
    - pip install httpx
    - upload_to_nexus.py
      --path app/build/outputs/apk/dev/debug/app-dev-debug.apk
      --repository "TestData/builds/Mail/Android/LatestDevDebug/"
      --filename "latest-mail-dev-debug.apk"
    - upload_to_nexus.py
      --path app/build/outputs/apk/androidTest/dev/debug/app-dev-debug-androidTest.apk
      --repository "TestData/builds/Mail/Android/LatestTestDevDebug"
      --filename "latest-mail-test-dev-debug.apk"

include:
  # Push the cache if it's the default branch
  - rules:
      - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    local: /ci/cache-policy-push-pull.yml

  # Do not push the cache if it's not the default branch (e.g. MRs)
  - rules:
      - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
    local: /ci/cache-policy-pull.yml

  - project: 'translations/generator'
    ref: master
    file: '/jobs/sync-crowdin.gitlab-ci.yml'

  - project: 'translations/generator'
    ref: master
    file: '/jobs/commit-locales.gitlab-ci.yml'

  - project: 'proton/mobile/android/proton-libs'
    ref: main
    file: '/ci/templates-shared/appetize-integration.yml'

  - local: '/ci/templates/base-jobs.gitlab-ci.yml'
