default:
  image: fabernovel/android:api-29-v1.4.1
before_script:
  - export JAVA_TOOL_OPTIONS="-Djava.net.useSystemProxies=true"

stages:
  - build
  - test

.build_job:
  stage: build
  before_script:
    - chmod +x gradlew
    - bundle install
  artifacts:
    paths:
      - app/build/outputs

buildDebug:
  extends: .build_job
  script:
    - bundle exec fastlane buildDebug

buildRelease:
  extends: .build_job
  script:
    - bundle exec fastlane buildRelease

testDebug:
  stage: test
  dependencies:
    - buildDebug
  script:
    - chmod +x gradlew
    - bundle exec fastlane test

