fullTest:
  device:
    - model: Pixel2.arm
      version: 33
    - model: b2q
      version: 31
    - model: crownqlteue
      version: 29
    - model: HWANE-LX2
      version: 28
    - model: walleye
      version: 27
    - model: NexusLowRes
      version: 24
smokeTest:
  device:
    - model: oriole
      version: 31
    - model: HWANE-LX2
      version: 28
    - model: G8142
      version: 25

