fullTest:
  device:
    - model: Pixel2
      version: 32
    - model: f2q
      version: 30
    - model: a10
      version: 29
    - model: phoenix_sprout
      version: 28
    - model: walleye
      version: 27
    - model: NexusLowRes
      version: 24
smokeTest:
  timeout: 30m
  device:
    - model: x1q
      version: 29
    - model: Pixel2
      version: 28
    - model: G8142
      version: 25

