fullTest:
  device:
    - model: walleye
      version: 28
    - model: walleye
      version: 27
    - model: flame
      version: 29
    - model: G8142
      version: 25
    - model: Nexus5X
      version: 23
quickTest:
  timeout: 30m
  device:
    - model: flame
      version: 29
    - model: Pixel2
      version: 28
    - model: Nexus5X
      version: 23

