.gradle_build_cache: &gradle-build-cache
  key:
    prefix: gradle-build-cache
    files:
      - gradle/wrapper/gradle-wrapper.properties
  paths:
    - ${CI_PROJECT_DIR}/build/gradle-build-cache
    - ${CI_PROJECT_DIR}/proton-libs/build/gradle-build-cache
  policy: pull

.build_job:
  stage: build
  extends: .checkout_core_job
  tags:
    - xlarge-k8s
  artifacts:
    paths:
      - app/build/outputs
  cache:
    - <<: *gradle-build-cache
      policy: pull-push

.firebase_test_job:
  stage: test
  dependencies:
    - build_debug
  tags:
    - small
  before_script:
    - bundle install
    - ./buildSrc/setup_firebase_gcloud.sh

.firebase_deploy_job:
  stage: deploy
  dependencies:
    - build_release
  tags:
    - small
  script:
    - echo $SERVICE_ACCOUNT_MAIL > /tmp/service-account.json
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
      when: never
