cache: &cache
  key: $CI_COMMIT_SHA
  paths:
    - ${CI_PROJECT_DIR}
  untracked: true

.ruby-cache: &ruby-cache
  key:
    prefix: ruby-cache
    files:
      - Gemfile.lock
  paths:
    - ${BUNDLE_GEM_PATH}
  policy: pull-push

.base_job:
  cache:
    - *cache
    - *ruby-cache

.build_job:
  stage: build
  extends: .base_job
  tags:
    - xlarge-k8s
  artifacts:
    paths:
      - app/build/outputs

.firebase_test_job:
  stage: test
  extends: .base_job
  dependencies:
    - build_dev_debug
  tags:
    - shared-small
  before_script:
    - ./scripts/setup_firebase_gcloud.sh
  cache:
    *cache

.firebase_deploy_job:
  stage: deploy
  extends: .base_job
  interruptible: false
  dependencies:
    - build_alpha_release
  tags:
    - shared-small
  before_script:
    - echo $SERVICE_ACCOUNT_MAIL > /tmp/service-account.json
    - ./scripts/release/generate_git_release_notes.sh /tmp/release_notes.txt
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
      when: never
  cache:
    *cache
