include:
  - local: '/ci/templates/cache.gitlab-ci.yml'

.ruby-job:
  image: ${CI_REGISTRY}/android/shared/docker-android:v1.0.0
  variables:
    BUNDLE_GEM_PATH: 'vendor/ruby'
  cache:
    - !reference [.ruby-cache, cache]
  before_script:
    - bundle config set path ${BUNDLE_GEM_PATH}
    - bundle config set without 'production'
    - bundle install
