variables:
  BUNDLE_GEM_PATH: 'vendor/ruby'

.ruby:
  before_script:
    - bundle config set path ${BUNDLE_GEM_PATH}
    - bundle config set without 'production'
    - bundle install
  cache:
    - key:
        prefix: ruby-cache
        files:
          - Gemfile.lock
      paths:
        - ${BUNDLE_GEM_PATH}
      policy: pull-push
