# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:android)

platform :android do

  desc "Execute static analysis"
  lane :analyse do
    gradle(task: "multiModuleDetekt")
  end

  desc "Assemble the debug apk"
  lane :assembleDebug do
    gradle(task: "assembleDevDebug")
  end

  desc "Assemble the test apk"
  lane :assembleTest do
    gradle(task: "assembleDevDebugAndroidTest")
  end

  desc "Assemble the release apk"
  lane :assembleRelease do
    gradle(task: "assembleRelease")
  end

  desc "Runs Unit Tests"
  lane :unitTest do
    gradle(task: "test")
  end

  desc "Publish build to firebase app testing"
  lane :deployToFirebase do
    firebase_app_distribution(
      app: '1:75309174866:android:1a431832c861474478cf8b',
      android_artifact_path: 'app/build/outputs/apk/dev/release/app-dev-release-unsigned.apk',
      # Service account is created on the CI from an env var each run (destroyed when finishing)
      service_credentials_file: '/tmp/service-account.json',
      groups: 'v6-dev-builds-testers'
    )
  end

  desc "Submit a new Closed-Testing Build in Alpha-v6 track to Play Store"
  lane :deployToPlayStoreAlpha do
    upload_to_play_store(track: 'alpha-v6', apk: 'app/build/outputs/apk/release/app-release.apk')
  end

end

